openapi: 3.0.0
info:
  title: API для взаимодействия с котом
  description: |
    Этот API позволяет узнать состояние кота и взаимодействовать с ним.
    Можно кормить, гладить, играть или оставить в покое.
  version: 1.0.0

servers:
  - url: https://cat-api-server.onrender.com
    description: Основной сервер

paths:
  /:
    get:
      summary: Приветствие от кота
      responses:
        '200':
          description: Сообщение приветствия
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Привет! Я кот-сервер. Накорми меня 😸

  /cat/status:
    get:
      summary: Получить текущее состояние кота
      responses:
        '200':
          description: Текущие настроение и последнее действие кота
          content:
            application/json:
              schema:
                type: object
                properties:
                  mood:
                    type: string
                    description: Настроение кота
                    example: голоден
                  last_action:
                    type: string
                    nullable: true
                    description: Последнее действие кота
                    example: съел рыбу

  /cat/feed:
    post:
      summary: Покормить кота
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedRequest'
      responses:
        '200':
          description: Кот был накормлен и доволен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Кот съел рыба и доволен 🐱
        '400':
          description: Неподходящий корм для кота
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /cat/pet:
    post:
      summary: Погладить кота
      responses:
        '200':
          description: Ответ кота на поглаживание
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Кот мурлычет и довольный 🐾

  /cat/play:
    post:
      summary: Поиграть с котом
      responses:
        '200':
          description: Кот рад поиграл
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Кот побегал за лазером и рад.

  /cat/annoy:
    delete:
      summary: Оставить кота в покое
      responses:
        '200':
          description: Кот лег спать
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Кот лег спать. Не трогай его.

components:
  schemas:
    FeedRequest:
      type: object
      required:
        - food
      properties:
        food:
          type: string
          description: Вид корма, которым кормят кота
          enum:
            - рыба
            - курица
            - корм
          example: рыба

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Код ошибки
          example: 400
        message:
          type: string
          description: Описание ошибки
          example: Кот фыркает. Он это не ест.
