openapi: 3.0.0
info:
  title: API для взаимодействия с котом
  description: |
    Этот API позволяет узнать состояние кота и взаимодействовать с ним.
    Можно кормить, гладить, играть или оставить в покое.
  version: 1.0.0

servers:
  - url: https://cat-api-server.onrender.com
    description: Основной сервер

tags:
  - name: Приветствие
    description: Приветственное сообщение от кота
  - name: Состояние
    description: Получение текущего состояния кота
  - name: Взаимодействие
    description: Взаимодействие с котом 
  - name: Отдых
    description: Оставить кота в покое

paths:
  /:
    get:
      tags:
        - Приветствие
      summary: Приветствие от кота
      responses:
        '200':
          description: Сообщение приветствия
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /cat/status:
    get:
      tags:
        - Состояние
      summary: Получить текущее состояние кота
      responses:
        '200':
          description: Текущие настроение и последнее действие кота
          content:
            application/json:
              schema:
                type: object
                properties:
                  mood:
                    type: string
                    description: Настроение кота
                    example: голоден
                  last_action:
                    type: string
                    nullable: true
                    description: Последнее действие кота
                    example: съел рыбов
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /cat/feed:
    post:
      tags:
        - Взаимодействие
      summary: Покормить кота
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedRequest'
      responses:
        '200':
          description: Кот был накормлен и доволен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Неподходящий корм для кота
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /cat/pet:
    post:
      tags:
        - Взаимодействие
      summary: Погладить кота
      responses:
        '200':
          description: Ответ кота на поглаживание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /cat/play:
    post:
      tags:
        - Взаимодействие
      summary: Поиграть с котом
      responses:
        '200':
          description: Кот рад поиграл
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

  /cat/annoy:
    delete:
      tags:
        - Отдых
      summary: Оставить кота в покое
      responses:
        '200':
          description: Кот лег спать
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:
    FeedRequest:
      type: object
      required:
        - food
      properties:
        food:
          type: string
          description: Вид корма, которым кормят кота
          enum:
            - рыбов
            - курицов
            - корм
          example: рыбов

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: Кот доволен и мурлычет 🐱

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Код ошибки
          example: 400
        message:
          type: string
          description: Описание ошибки
          example: Кот фыркает. Он это не ест.

    ServerErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Код ошибки
          example: 500
        message:
          type: string
          description: Описание внутренней ошибки сервера
          example: Внутренняя ошибка сервера. Попробуйте позже.
